[env]
# for building librime-sys
LIBRIME_INCLUDE_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/librime/dist/include"
LIBRIME_LIB_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/librime/dist/lib"

[tasks.pre-build]
condition = { platforms = ["mac", "windows"], files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/librime/version-info.txt"] }
run_task = { name = "fetch-rime-artifact" }

[tasks.fetch-rime-artifact]
mac_alias = "fetch-rime-artifact-mac"
windows_alias = "fetch-rime-artifact-windows"

[tasks.fetch-rime-artifact-mac]
env.rime_release = "1.11.0"
env.rime_artifact = "rime-76a0a16-macOS-universal.tar.bz2"
env.rime_artifact_checksum = "1c70a25eedc574e915be75c44fc4386be12d868945e40b3f86afb64dfddea7b7"
run_task = { name = ["download-rime-artifact", "extract-rime-artifact-posix"] }

[tasks.fetch-rime-artifact-windows]
env.rime_release = "1.11.0"
env.rime_artifact = "rime-76a0a16-Windows-msvc-x64.7z"
env.rime_artifact_checksum = "32908951837501da8957d350765c9c3786c3998fa17fbdfc02b7c3e7aaaf5780"
run_task = { name = ["download-rime-artifact", "extract-rime-artifact-windows"] }

[tasks.download-rime-artifact]
script_runner = "@duckscript"
script = '''
download_file = set ${CARGO_MAKE_WORKING_DIRECTORY}/${rime_artifact}
if not is_path_exists ${download_file}
  echo downloading ${rime_artifact}...
  response_size = http_client --output-file ${download_file} https://github.com/rime/librime/releases/download/${rime_release}/${rime_artifact}
  assert ${response_size}
  echo downloaded ${response_size} bytes to ${download_file}
else
  echo found ${download_file}
end
checksum = sha256sum ${download_file}
echo checksum: ${checksum}
assert_eq ${checksum} ${rime_artifact_checksum}
'''

[tasks.extract-rime-artifact-posix]
script = '''
mkdir -p "${CARGO_MAKE_WORKING_DIRECTORY}/librime"
tar -xjvf "${CARGO_MAKE_WORKING_DIRECTORY}/${rime_artifact}" -C "${CARGO_MAKE_WORKING_DIRECTORY}/librime"
'''

[tasks.extract-rime-artifact-windows]
command = "7z"
args = ["x", "-y", "-o${CARGO_MAKE_WORKING_DIRECTORY}/librime", "${CARGO_MAKE_WORKING_DIRECTORY}/${rime_artifact}"]
